kind: MLApp
metadata:
  name: h2o-ai
spec:
  default_mount_path: /notebooks
  default_read_only: false
  package_manager: pip3
  packages:
  - manager: pip3
  tasks:
  - name: h2o-test
    resources:
    - command: python src/example.py {{ .app_name }}-h2o-flow --port 80
      default_volume_mapping: true
      images:
        cpu: kuberlab/h2o.ai:latest
        gpu: kuberlab/h2o.ai:latest
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR

  uix:
  - default_volume_mapping: true
    displayName: H20 Flow
    images:
      cpu: kuberlab/h2o.ai:latest
    name: h2o-flow
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 54321
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 64Mi

  volumes:
  - clusterStorage: '{{ .storage.value }}'
    name: training
  - gitRepo:
      repository: {{ gitRepo .src.value }}
      accountId: '{{ .src.accountId }}'
      revision: '{{ .src.revision }}'
    name: src
    subPath: {{ gitSubPath .src.value }}
  - clusterStorage: '{{ .storage.value }}'
    isLibDir: true
    name: lib
  - clusterStorage: '{{ .storage.value }}'
    mountPath: /notebooks
    name: code
    subPath: code
  - name: data
    {{- if .dataset.value }}
    datasetFS:
      workspace: {{ .dataset.workspace }}
      dataset: {{ .dataset.value }}
      version: {{ .dataset.version }}
    {{- else }}
    clusterStorage: {{ .storage.value }}
    {{- end }}
