
storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage


src:
  value: https://github.com/kibernetika-ai/h2o
  accountId: ''
  revision: ''
  wizard:
    name: "Source Code"
    kind: git

dataset:
 value: ''
 version: ''
 workspace: ''
 wizard:
   name: "Dataset to connect"
   kind: dataset
